apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite-prod-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satellite-prod-v2
      track: blue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: satellite-prod-v2
        track: blue
    spec:
      containers:
      - name: satellite
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
             path: /
             port: 8080
          failureThreshold: 6
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 6
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1 
