apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  rules:
  - http:
      paths:
      - path: /sat-1/*
        backend:
          serviceName: satellite-dev-svc
          servicePort: 80
      - path: /sat-2/*
        backend:
          serviceName: satellite-dev-svc-2
          servicePort: 80
