apiVersion: v1
kind: Service
metadata:
  name: satellite-dev-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: satellite-dev
---

apiVersion: v1
kind: Service
metadata:
  name: satellite-dev-svc-2
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: satellite-dev-2
